import "./globals.css";
import NavBar from '../app/components/NavBar'
import Footer from '../app/components/Footer'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: ['hotel','restaurant','resort','five stars'],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet"></link>
      </head>
      <body>
       <NavBar/>
        {children}
      <Footer/>
      </body>
    </html>
  );
}
